### ISSUE TITLE
Deserializing Enums sent from Java/Swift client throwing ClassCastException

### ISSUE THREAD

**Issue by kirkeaton** [foam-framework/foam2#1145]
Enum value is sent to the server as an integer and isn't converted back to an Enum so a ClassCastException occurs.

```
2018.04.06.14.14.04,DEBUG,[Service],transactionDAO,returning skeleton exception,java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Enum
    at java.lang.Enum.compareTo(Enum.java:55)
    at foam.util.SafetyUtil.compare(SafetyUtil.java:24)
    at foam.mlang.predicate.Neq.f(Neq.java:15)
    at foam.mlang.predicate.And.f(And.java:16)
    at foam.dao.PredicatedSink.put(PredicatedSink.java:95)
    at foam.dao.MapDAO.select_(MapDAO.java:90)
```

**Comment by kgrgreer** [comment]
Parsed with AnyParser which doesn't know the difference between Integers and Enums.

**Comment by kgrgreer** [comment]
JS works because it outputs the enum as a full FObject, as shown below:

e = foam.mlang.Expressions.create().EQ(net.nanopay.tx.model.Transaction.STATUS, net.nanopay.tx.model.TransactionStatus.PENDING);

foam.json.stringify(e);
"{class:"foam.mlang.predicate.Eq",arg1:{class:"__Property__",forClass_:"net.nanopay.tx.model.Transaction",name:"status"},arg2:{class:"foam.mlang.Constant",value:{class:"net.nanopay.tx.model.TransactionStatus",ordinal:0,name:"PENDING",label:"Pending"}}}"

**Comment by kgrgreer** [comment]
However, when serializing an FObject property, JS still uses the compact format:

t.status = net.nanopay.tx.model.TransactionStatus.REFUNDED;
t.toJSON();
{instance_: {…}, name: "REFUNDED", label: "Refunded", ordinal: 4}

**Comment by kgrgreer** [comment]
Script to test Java support:
e = net.nanopay.tx.model.TransactionStatus;

print(e.SENT.getClass().getName());

t = new net.nanopay.tx.model.Transaction();
print(t.toString());
print(t.toJSON());
m = foam.mlang.MLang.EQ(net.nanopay.tx.model.Transaction.STATUS, net.nanopay.tx.model.TransactionStatus.PENDING);
print(m.toJSON());
