### ISSUE TITLE
Cloned FObject does not equal original FObject in Java

### ISSUE THREAD

**Issue by kirkeaton** [foam-framework/foam2#1353]
```
fobject.equals(fobject.fclone())
```
where fobject is the same object returns false. 
Since no modifications have been done, the objects should be the same.

**Comment by kgrgreer** [comment]
import foam.nanos.auth.User;

u1 = new User();

print(u1.fclone().equals(u1));
print(u1.equals(u1.fclone()));
print(u1.fclone().compareTo(u1));
print(u1.compareTo(u1.fclone()));

print(u1.toJSON());
print(u1.fclone().toJSON());

produces output:

false
false
1
-1
{birthday=null, lastLogin=null, questionnaire=null, invitedBy=null, additionalDocuments=null, spid=null, businessProfilePicture=null, transactionLimits=null, businessAddress=null, passwordLastModified=null, group=null, address=null, passwordExpiry=null, businessSectorId=null, mobile=null, disabledTopicsEmail=null, businessTypeId=null, profilePicture=null, phone=null, principalOwners=null, businessRegistrationDate=null, accounts=null, lastModified=null, businessPhone=null, disabledTopics=null}
{"class":"foam.nanos.auth.User"}
{"class":"foam.nanos.auth.User","id":0,"enabled":true,"firstName":"","middleName":"","lastName":"","legalName":" ","organization":"","department":"","email":"","emailVerified":false,"phoneNumber":"","type":"","accounts":[],"language":"en","timeZone":"","desiredPassword":"","password":"","previousPassword":"","note":"","businessName":"","bankIdentificationCode":"","businessHoursEnabled":false,"disabledTopics":[],"disabledTopicsEmail":[],"website":"","twoFactorEnabled":false,"twoFactorSecret":"","deviceToken":"","branchId":"","clearingId":"","invited":false,"previousStatus":0,"status":0,"compliance":0,"additionalDocuments":[],"principalOwners":[],"jobTitle":"","principleType":"","portalAdminCreated":false,"welcomeEmailSent":false,"businessRegistrationNumber":"","businessRegistrationAuthority":"","onboarded":false,"createdPwd":false,"inviteAttempts":0,"transactionLimits":[]}


So the problem is that unset values get set to their default/factory values when cloned.

**Comment by kirkeaton** [comment]
Fixed by: https://github.com/foam-framework/foam2/pull/1372
