### ISSUE TITLE
Support spread-syntax in function arguments

### ISSUE THREAD

**Issue by mdittmer** [foam-framework/foam2#194]
Support for arrow-functions is [mostly implemented](https://github.com/foam-framework/foam2-experimental/commits/consumable), but type checking fails when spread syntax is use.

Example:

```js
function foo(a, b, c, ...rest) {
  /* ... */
}
const bar = (x, y, z, ...rest) => /* ... */;
```

It would be a good start to gracefully recognize and ignore spread syntax. Ideally, typing for such cases can be adequately expressed and these functions can by type checked.

**Comment by jacksonic** [comment]
Since this gives the equivalent of var args, picking up the dots (which probably fail the matcher at the moment) will let us assign 'repeated' to that last argument and capture valid calls to the function.

**Comment by jacksonic** [comment]
Also: The arrow syntax for type-checked functions is not supported, but in the case of type checking methods you wouldn't want to use it. It doesn't bind 'this', and is intended for use inside other functions that have a valid 'this' (or for expressions that don't require a 'this' at all). Methods and other contextually-aware class members should still be expressed as full functions.

We could extend support to arrow syntax, but it would only come into play where the user wanted to install it manually, adding a lot of baggage to an otherwise lightweight declaration.

**Comment by jacksonic** [comment]
Stable repo now has '...' support

**Comment by jacksonic** [comment]
A side note: ES2016 introduces destructuring, which ends up with constructs like object declarations and expressions in the function args line. When we get to this, it might end up requiring a full parser to support.
