### ISSUE TITLE
Finalize *:* relationship convenience property design

### ISSUE THREAD

**Issue by mdittmer** [foam-framework/foam2#299]
A `Foo <--> Bar` *:* relationship has convenience properties `foo.bars` and `bar.foos` on objects that come out of the relationship's DAOs. Currently, these properties are strangely hybrid DAOs that return `Bar` or `Foo` objects on select, but adapt said objects to `FooBarJunction` objects and wrie to the join table on `put. Due to unclear/inconsistent the semantics for reading and writing over these properties it's been proposed that they be redesigned to contain explicit references to Junction and non-Junction DAOs.

**Comment by mdittmer** [comment]
@adamvy it looks like tip of tree contains `foo.bars.put()` = put-to-`barDAO`-then-put-to-`fooBarJunctionDAO`. @kgrgreer do we have a consensus on how we want this to work? I know there was talk of exposing `bars.items` and `bars.junction` or similar.

**Comment by adamvy** [comment]
I don't know if we have concesus yet, but I like the idea of exposing both the junction and target.  I was working on a patch that did this but haven't finished it yet.

**Comment by kgrgreer** [comment]
What if instead of having a holder object with two properties: junction and
target, we just give you the targetDAO, like normal, but then extend the
ManyToManyRelationshipDAO with a 'junction' property which gives you the
junction DAO directly?

invoice.lineItems.select()
Invoice.lineItems.junction.select()

and/or add/removeKey() or set/unset methods:

invoice.lineItems.set(4)
invoice.lineItem.unset(4)

This is effectively the same thing, but I think it somehow reads nicer and
is more in keeping with properties having single values.

Or, what did we call that when we do property$version? So we could have
invoice.lineItems$junction

**Comment by adamvy** [comment]
On April 27, 2017 11:40:47 AM EDT, Kevin Glen Roy Greer <notifications@github.com> wrote:
>What if instead of having a holder object with two properties: junction
>and
>target, we just give you the targetDAO, like normal, but then extend
>the
>ManyToManyRelationshipDAO with a 'junction' property which gives you
>the
>junction DAO directly?
>
>invoice.lineItems.select()
>Invoice.lineItems.junction.select()
>
>and/or add/removeKey() or set/unset methods:

I was thinking of adding .add() and .remove() methods to the relationship object.

Invoice.lineitems.add(someExistingLineItem)

Or by ID like you did.

It could also have .select() and .find() methods which just forward to the targetDAO.  But it's a different overall interface from the dao so it's less likely to get confused or used as a dao improperly.


>
>invoice.lineItems.set(4)
>invoice.lineItem.unset(4)
>
>This is effectively the same thing, but I think it somehow reads nicer
>and
>is more in keeping with properties having single values.
>
>Or, what did we call that when we do property$version? So we could have
>invoice.lineItems$junction
>

**Comment by kgrgreer** [comment]
But if you can do select(), then you would also want skip(), limit(),
orderBy(), and where(), which you would need to re-implement because helper
classes like OrderedDAO take DAO's, not Relationships. Unless you break the
code out of DAO/AbstractDAO into Selectable/AbstractSelectable, but that's
probably more complexity than is merited.

**Comment by adamvy** [comment]
On Thu, Apr 27, 2017 at 12:28 PM, Kevin Glen Roy Greer <
notifications@github.com> wrote:

> But if you can do select(), then you would also want skip(), limit(),
> orderBy(), and where(), which you would need to re-implement because helper
> classes like OrderedDAO take DAO's, not Relationships. Unless you break the
> code out of DAO/AbstractDAO into Selectable/AbstractSelectable, but that's
> probably more complexity than is merited.


Yeah that's a bad idea, forget select() on that object.


>
>

**Comment by adamvy** [comment]
The fact that Mike, Mark, and myself were all tripped up by the existing
ManyToManyRelationshipDAO behaviour though suggests we need something, but
I'm willing to accept that maybe its just better developer education.

At the end of the day, for my purposes I guess I don't care what the
interface is so much, I don't plan to be coding against it much by hand,
only a few times for a few reusable views, which I will re-use for
everything :)

**Comment by mdittmer** [comment]
Do we have precedence for a `ReadOnlyDAO` (interface, or implementation of `DAO` that throws on write operations)?

I need that for my projects anyway. So far, I've thrown custom errors on `put`/`remove`/`removeAll` each time I need it.

I don't think it's unreasonable to some kind of `add`/`unadd` (`relate`/`unrelate`?) interface that's separate from the `DAO` interface, and have `order.lineItems` implement both `ReadOnlyDAO` and `Relatable`. This means we need not throw out things like `skip`, `limit`, etc., but we also don't get confused about which collection we're `put`/`remove`ing to when operating on `lineItems`.

**Comment by mcarcaso** [comment]
I have an approach here that I've been working on and using that seems to
meet all of my needs. Currently, the relationship creates a DAOProperty
which is either a RelationshipDAO or ManyToManyRelationshipDAO but, as
we've found, sometimes those DAOs alone don't expose everything one might
need to deal with the relationship data. At a high level, my proposed
design does the following:

Replace the DAOProperty that's added with an FObjectProperty
The FObject that's exposed has the following:

   - dao - the RelationshipDAO or ManyToManyRelationshipDAO
   - targetDAO - the DAO that the RelationshipDAO proxies to.
   - junctionDAO - optional and only really applies to *:* relationships

In the context of a chat app, this is how it would all look:
Models are User and Conversation (Message would be a thing too but let's
ignore that for now)

User:Conversation is *:* (this creates a UserConversationJunction model)

user.conversations.dao has all of the conversations that this user is in
user.conversations.targetDAO has all conversations
user.conversations.junctionDAO has all links between user and conversation

conversation.users.dao has all of the users in the conversation
conversation.users.targetDAO has all users
conversation.users.junctionDAO has all links between user and conversation
(same as user.conversations.junctionDAO)

Adding a user to a conversation could be done via
conversation.users.dao.put (or conversation.users.junctionDAO.put but
that's a little uglier)
Removing a user from a conversation could be done via
conversation.users.junctionDAO.remove
Removing a user completely could be done via
conversation.users.targetDAO.remove

I'm not sure what conversation.users.dao.remove should do. I think the
options are, do nothing, remove the relationship, or remove the
relationship and the object. At this point it doesn't really matter to me
because I can accomplish any of the behaviour by using the targetDAO or
junctionDAO directly if need be.

The downside here is that conversation.users isn't a DAO itself which can
be a little awkward and requires you to know that it's a relationship but
this has been the most flexible approach I've tried so far. What do y'all
think?

**Comment by mdittmer** [comment]
I still think there's a mismatch between how _ordinary DAOs_ work and how these _special DAOs_ work, that bothers me. For example, `conversation.users.dao.select()` will produce `User` objects, filtered by association with the `conversation` in the join table. However, `put()`ing to it will (possibly add the `User` to the target DAO? and) construct a `UserConversationJunction` based on the `conversation` and the `User` being `put()`, and `put()` that to a different DAO.

Maybe I'm splitting hairs here; maybe this extra data management is just an _implementation detail_ of the `conversation.users.dao` DAO.

As to the question of `remove()`, if we did go down this road I would expect `conversation.users.dao.remove()` to dissociate the conversation and user, and delete the user **iff** `put()`ing also `put()`s to the user DAO -- the "possibly..." parenthetical above.

Thoughts?

**Comment by adamvy** [comment]
We could disable .put() and .remove() on conversation.users.dao, and
require you to manually create the user and also the association.

I think we conversation.users.put() should either create the user and the
association, or should throw and exception.

**Comment by mcarcaso** [comment]
Disabling put and remove on conversation.users.dao definitely simplifies
all of this and I wouldn't be against taking that approach since you have
the means to put into these DAOs via the targetDAO and junctionDAO. I think
we should start with this approach since it should unblock all of us from
making progress with relationships.

**Comment by mdittmer** [comment]
I agree. This side-steps the messy write semantics, while still providing access to the "raw" DAOs for "ordinary" `put()` and `remove()`.

**Comment by kgrgreer** [comment]
I endorse this design. Either disable put() and remove(), You might also
consider adding set() and unset() methods to the FObject which let you add
target object junctions by just providing the target object or target.id.

**Comment by adamvy** [comment]
Mike and I were just discussing add set/unset or add/remove as we were
thinking of naming them.

**Comment by kgrgreer** [comment]
On 3 May 2017 at 13:31, adamvy <notifications@github.com> wrote:

> Mike and I were just discussing add set/unset or add/remove as we were
> thinking of naming them.
>
>
Good, I'm redundant then :-).

**Comment by adamvy** [comment]
haha

**Comment by mdittmer** [comment]
Looks like the updated design will land with #318

**Comment by kgrgreer** [comment]
Done.
