### ISSUE TITLE
Don't output default values, nulls, or empty arrays in JSON Output

### ISSUE THREAD

**Issue by kgrgreer** [foam-framework/foam2#74]

**Comment by adamvy-google** [comment]
Should we really avoid ouputting nulls and empty arrays?  I think we should target default values only and find a better way to expression the default value for array properties.

**Comment by kgrgreer** [comment]
We should avoi doutputting nulls and empty arrays when those are the default values, not otherwise. The same as we did in FOAM1 (and the previous 10 versions).

**Comment by adamvy-google** [comment]
> when those are the default values

That's my point, is we don't currently have a way to differentiate between the "default value" of an array empty array or being set to the empty array.

When the default value of a property _is_ null, or empty array, then we should absolutely not output it, but that is just an extension of the "don't output default value" policy.

**Comment by adamvy-google** [comment]
After discussions, the real problem is that hasOwnProperty is not what we wanted to check most of the time.

The real user interface that people should use is "isDefaultValue()" because what they usually actually care about is if the current value is the default one, not whether something is being stored for it.

So we will add isDefaultValue, and let hasOwnProperty continue  to be "inconsistent" but encourage users to use isDefaultValue as its the "right" interface most of the time.

**Comment by adamvy-google** [comment]
We should also add factory back to array properties.
